### ISSUE TITLE
Where are Password Gorilla database files stored? 

### ISSUE THREAD

**Issue by ajcamp** [zdia/gorilla#207] opened 2019-12-02 18:48 UTC
Sorry, I'm sure this has been asked before but the search doesn't find the thread. 

I created a password database using all defaults but I can't locate the database after reboot. 

Where is the Gorilla password database located on Windows 7 Professional 

I've opened and closed Gorilla a few times before rebooting, and it always opened the database, but after reboot, it didn't.

Thanks for any help

**Comment by rich123** [comment] 2019-12-02 19:17
Github's search ability leaves a lot to be desired -- but I can't help their lack of ability to build a workable search.

As for where a file is saved, the default, if you did not change anything, is the current working directory of the Gorilla process.  Which on windows can be whatever windows decides to assign.

I see two ways to find your existing file:

1) go through just enough creation of a new DB to get to saving the DB, then when the dialog appears asking you to give it a name, make note of which directory is used as the default location.  It is very likely your existing passwords file will be in that same location.

2) presuming you remember the name you used for the file, search your drive for files with that name (you can do this from the file explorer by putting the search string into the 'find' box on the top, and adding a star (*) to find all variants.  (This at least works with W10, I'm presuming something similar works with W7.)

So, if you remember you named the file "passwords" then you could find it by starting at C: in the file explorer window, and entering "password*" in the find box, pressing return, and waiting while windows searches the drive.  Note that this may take some time (length depends upon whether you have a traditional spinning platter disk or a faster SSD disk), and it may also return other results, so you'll likely have to look through what returns to find your passwords file.

Then, once you do find where it went I suggest you create a known location to store it (I.e., "My Documents/Passwords" or something you are sure to remember) and move the file to that known location.  Then ask Gorilla to open the file by navigating to that location and choosing the file, after which Gorilla should remember the location.  You will want to explicitly exit Gorilla at least once after you do open the file to be sure it has saved its state data that it uses to remember where you last saved/opened a passwords file from.

**Comment by rich123** [comment] 2019-12-04 19:06
Were you able to locate where your password file was stored?

**Comment by ajcamp** [comment] 2019-12-09 15:47
Hi Rich,

It turns out there is a bug in Password Gorilla. I have the DB set to
create .PSAFE3 database types, but the password database was created
without a file extension at all. That's why I couldn't find it.

Thanks
Andrew

**Comment by rich123** [comment] 2019-12-09 16:12
Which version of Password Gorilla are you running?
I just tested creating a new database with 1.6.0-beta-2 without manually adding any extension, and ".psafe3" was automatically added.  Can you test as well and see what happens?
Also, how did you go about saving the file, and what did the rest of the filename you used that lacked ".psafe3" look like?

**Comment by ajcamp** [comment] 2019-12-09 16:16
Version 1.5.3.7

**Comment by ajcamp** [comment] 2019-12-09 16:16
Windows 7 Professional

**Comment by rich123** [comment] 2019-12-09 16:44
Ok, I was just able to recreate this in my W7 VM.  Under Linux I get a .psafe3 extension added if I leave an extension off in the save-as dialog.  Under W7 I do not get an auto-added .psafe3 extension.
Now I need to go figure out why the difference between Linux and W7.

**Comment by ajcamp** [comment] 2019-12-09 16:51
Ok, so you were able to duplicate my issue. Thanks.

**Comment by rich123** [comment] 2019-12-09 17:51
Yes, I can duplicate the issue, and I've found the cause now.
The Tk API call to open a dialog to obtain a filename to save a new database into automatically adds an extension under Linux when one is omitted.
But under W7, the exact same API call does not automatically add an extension.

**Comment by rich123** [comment] 2019-12-09 19:23
Recent commit fixed the issue in my VM W7 test.  Closing out issue now.

**Closed by rich123** 2019-12-09 19:23 UTC
