### ISSUE TITLE
Cannot save more than 64 entries

### ISSUE THREAD

**Issue by pablanche** [zdia/gorilla#182] opened 2018-02-12 18:15 UTC
Running Gorilla on Ubuntu 17.10
Tried to enter one more login to my database and have the following error message:
`couldn't execute "/sbin/ifconfig": no such file or directory
couldn't execute "/sbin/ifconfig": no such file or directory
    while executing
"exec /sbin/ifconfig"
    (procedure "dump" line 2)
    invoked from within
"dump"
    (procedure "::nettool::mac_list" line 3)
    invoked from within
"::nettool::mac_list"
    (procedure "::nettool::hwid_list" line 3)
    invoked from within
"::nettool::hwid_list"
    (procedure "generate_tcl_machinfo" line 36)
    invoked from within
"generate_tcl_machinfo"
    (procedure "generate_tcl" line 7)
    invoked from within
"generate_tcl"
    (procedure "generate" line 6)
    invoked from within
"generate"
    (procedure "uuid::uuid" line 7)
    invoked from within
"uuid::uuid generate"
    (procedure "PopulateRecord" line 20)
    invoked from within
"PopulateRecord [ set newrn [ $::gorilla::db createRecord ] ] "
    (procedure "Ok" line 30)
    invoked from within
"Ok"
    (in namespace inscope "::gorilla::LoginDialog::0" script line 1)
    invoked from within
"namespace inscope ::gorilla::LoginDialog::0 Ok"
    invoked from within
".nmLoginDialog0.bf.top.ok invoke "
    invoked from within
".nmLoginDialog0.bf.top.ok instate !disabled { .nmLoginDialog0.bf.top.ok invoke } "
    invoked from within
".nmLoginDialog0.bf.top.ok instate pressed { .nmLoginDialog0.bf.top.ok state !pressed; .nmLoginDialog0.bf.top.ok instate !disabled { .nmLoginDialog0.bf..."
    (command bound to event)`

After acknowledging the error message, if I try to save the database I have another error message:
"Failed to save password database as /home/Database.psafe3: record 64 does not exist".
If I delete one record (login) I can save and there is no error message. There is something special with that 64th record.

**Comment by rich123** [comment] 2018-02-12 18:49
Given the first error (the /sbin/ifconfig one) the second error (magic number 64) might just be a side effect of the first.

The first error was fixed in commit 6284d86ebafc8a65ad7e1fc1626282317d608788.  That commit is on the current dev branch (pre160) but is not yet in the currently released package that Ubuntu uses.

My best suggestion to you at the moment is to upgrade to the pre160 branch (which will make the /sbin/ifconfig error go away).  When it goes away, the magic 64 might also go away as well (because your 64th might just have been the one that failed due to the first error [/sbin/ifconfig]).  But it is easy enough to find out (if a bit of boring work).  Create a blank test file, then add about 62 entries, then save, add one, save, add one until past the 64 boundary and see if the magic number 64 appears independent of the first error.

**Comment by rich123** [comment] 2018-02-12 19:05
Just tested creating a new, empty, DB file.   I then inserted 60 new records.  With record 61 I inserted one record, then did a save, the repeated insert/save one at a time up to 69 records.  No error message at any one of the save points.

So it very much looks like the magic 64 number value was caused by the UUID generation failure from the first error message (the one about parsing /sbin/ifconfig).

**Comment by pablanche** [comment] 2018-02-12 19:08
Agree. The 64th error should be conditioned to the /sbin/ifconfig error.
How to  upgrade to the pre160 branch?

**Comment by rich123** [comment] 2018-02-12 19:30
Since you are on Ubuntu, you should be able to go to the github main page for gorilla, and press the 'branch selector" button:
![master](https://user-images.githubusercontent.com/305956/36115350-c05e27ae-102a-11e8-96de-22368714e0bd.png)
Press it and select the pre160 branch entry:
![select](https://user-images.githubusercontent.com/305956/36115367-ce4082f4-102a-11e8-906f-24be18c0abde.png)
After github updates, the button should look like this:
![pre160](https://user-images.githubusercontent.com/305956/36115393-dc8da026-102a-11e8-81a5-608becdb3372.png)
Then push the down arrow on the "clone or download" button and pick the "download.zip" option:
![download](https://user-images.githubusercontent.com/305956/36115421-f2fcbd7e-102a-11e8-9236-b0c200f706a0.png)
Then, unpack the zip somewhere, go into the gorilla/sources directory, and launch the gorilla.tcl file located therein. 

If you already have the Ubuntu Tcl/Tk packages installed, this will launch gorilla.  If you don't have the Ubuntu Tcl/Tk packages, then install them first from the Ubuntu software install tool.

**Comment by pablanche** [comment] 2018-02-12 20:49
Works!
Plus, the logins are now listed regardless of capitalized letters. Much better.
Thanks for the prompt help.

**Comment by rich123** [comment] 2018-02-12 21:33
You are welcome.

I'll go ahead and close this issue now that the item has been resolved.

**Closed by rich123** 2018-02-12 21:33 UTC
