### ISSUE TITLE
Cannot copy username to clipboard: No username defined (on Linux)

### ISSUE THREAD

**Issue by PorcelainMouse** [zdia/gorilla#176] opened 2017-11-15 05:10 UTC
I have several entries, in a database I've used for many many years, which are giving the error: "Cannot copy username to clipboard: No username defined" even though the entry clearly shows a username defined.  Is anyone else seeing this on Linux?

**Comment by rich123** [comment] 2017-11-15 10:43
Interesting.  Which version are you running when you get this message for these entries?

**Comment by PorcelainMouse** [comment] 2017-11-16 06:41
I'm on the head of the pre160 branch and have been for a while.  commit c28c057115045b9149b5877e0a9e265a3c5bd3ad.  BTW, there isn't any tclsh8.5 on my system (or distribution).  I only have 8.6.  Is that a problem?

**Comment by rich123** [comment] 2017-11-16 11:23
8.6 shouldn't be an issue.  One of my systems has 8.6.1 and pre160 does not trigger this error for me (unless, of course, I actually have an entry with no username defined in it).  So we will have to dig a little deeper.

So, next question, are you performing the copy using the right-click context menu, the top bar drop down menu, or the keyboard shortcut (they should all call the same code, but it is worth my being able to test exactly the way you get the error to appear).

Second, given that you are on pre160, that indicates you are running the source.  Are you willing to make some edits to a copy of gorilla.tcl to try to trace what is happening?

If yes, start by copying gorilla.tcl to another name so you can edit/run the other file without damaging the original.  Next, open the copy in an editor and search for this string: `proc GetSelectedUsername`.

Then, add two "error" calls like shown below (the "error" calls are the insertions).  I picked the string parameters below on purpose, to differentiate why the request for the user name is returning not-found.:

```tcl
  proc GetSelectedUsername {} {
    # Retreive the username of the selected item in the treeview
    if {[catch {set rn [gorilla::GetSelectedRecord]}]} {
      error "GetSelectedUsername: gorilla::GetSelectedRecord returned an error"
      return
    }
    if {![$::gorilla::db existsField $rn 6]} {
      error "GetSelectedUsername: db existsField returned not found for field 6"
      return
    }
    return [ ::gorilla::dbget user $rn ]
  }
```

Then manually launch the edited code, and try a copy username for both a working, and non-working, record and report which of the two errors above happens for the non-working record.

**Comment by PorcelainMouse** [comment] 2017-11-19 21:32
Thank you for your help!

I'm using the right-click mouse menu, usually.  I can easily try the other methods, of course, and get back to you on that.

I'm happy to do any testing.  I'll try your patch and see what happens.  More soon.

**Comment by PorcelainMouse** [comment] 2017-11-20 05:57
First of all, I get the same result with all three methods.
Secondly, here is the error I get after your patch:
```
GetSelectedUsername: db existsField returned not found for field 6
GetSelectedUsername: db existsField returned not found for field 6
    while executing
"error "GetSelectedUsername: db existsField returned not found for field 6""
    (procedure "GetSelectedUsername" line 9)
    invoked from within
"GetSelected$activeSelection "
    (procedure "finish" line 13)
    invoked from within
"finish $mult"
    (procedure "::gorilla::CopyToClipboard::Username" line 3)
    invoked from within
"gorilla::CopyToClipboard Username"
    (procedure "gorilla::PopupCopyUsername" line 2)
    invoked from within
"gorilla::PopupCopyUsername"
    invoked from within
".popupForLogin invoke active"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke active]"
    (procedure "tk::MenuInvoke" line 50)
    invoked from within
"tk::MenuInvoke .popupForLogin 1"
    (command bound to event)
```

**Comment by rich123** [comment] 2017-11-20 10:55
Thanks, that helped in seeing past what I actually wrote instead of what should have been present.

I'm going to guess, the specific entries that complain "no username" happen to have a username, but no password, right?  I was just able to recreate the issue here with a test entry that had a username, but was missing a password.

The cause is a single character bug, one that has been hidden for quite some time because, by being a *password* manager, almost all entries everywhere have at least a password defined.  At least in my use cases, I don't think I have a single entry that lacks a password.  I've several with no url's, or no usernames, but always a password.

Try this fix on your edited code first.  In the proc "GetSelectedUsername", about half way it says:

$::gorilla::db existsField $rn 6

Change the 6 to a 4.

Then test the code.  I suspect the error message will go away.  Field 6 in the PasswordSafe V3 format is the password.  The username is field 4.  The "get username" proc was testing for, and complaining about a missing password.  Or, at least, that is what I've found based upon your help.

If the edit removes all the complaints for your copy, then edit your gorilla.tcl to make the same change (just be careful, the GetSelectedPassword proc has the same code, but should remain as "6".

I'll push a patch to the pre160 branch soon (where the latency of 'soon' is likely defined as "within next few days").

**Comment by rich123** [comment] 2017-11-20 10:57
Ok, instead of a 'gorilla' emojii above (github flavored markdown strikes again) that should have read:
$ :: gorilla ::db
only without the spaces around "gorilla".

**Comment by PorcelainMouse** [comment] 2017-11-20 22:14
You are correct.  I think all of these entries don't have passwords.  Although, I've been doing this for a long time and I didn't notice this before.  I'm almost certain this worked at some point.  I'm doing it frequently, now, because I have e-mail service that lets me generate e-mail address and I need to keep track of some of them.

I changed GetSelectedUsername to check field 4 instead of 6 and now I get the expected behavior.

Thanks for your help!  You probably don't need me to send you a pull request, but let me know if that's helpful.

**Comment by rich123** [comment] 2017-11-21 17:28
No PR needed for this minor fix, but thanks for the offer.

It likely did work at some point.  That point would be (guessing) before I wrote this section of code that pulled together all the different ways of performing "copy to clipboard" into a single common code path.  Without digging back through git history I can't tell you when that was.

**Comment by rich123** [comment] 2017-11-21 19:27
Commit 4614b5e5ea97ac598ba5d957b277982d5c1b6443 makes the change to the tip of pre160 branch.  Closing this issue now.

**Closed by rich123** 2017-11-21 19:27 UTC
